### PR TITLE
Update dependencies to v2, try with noarch

### PR DESCRIPTION
**Pull request by maresb**
Now that TF2.4 is on conda-forge we have a chance to revive this.

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
This is blocking me from creating a recipe for tensorflow-lattice: https://github.com/conda-forge/staged-recipes/pull/14601

As far as I can tell, this PR looks ready to merge.

**Comment by maresb** [comment]
Hello @asmith26 and @marcelotrevisani, if you could find the time, I'd really appreciate a review on my PR so that I can proceed with tensorflow-lattice. Thanks so much!

**Review by asmith26 — APPROVED** [review]
Hi @maresb, thanks very much for this, all looks good - if I'm honest I'm a little out of touch with the dm-sonnet library. Consequently, you may like to add yourself as a maintainer for this going forward: https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list

Many thanks again :)

**Comment by maresb** [comment]
Great, thanks @asmith26! I just added myself as a maintainer as you suggested.

**Review by marcelotrevisani — APPROVED** [review]

**Comment by maresb** [comment]
Thanks @marcelotrevisani!!! 

Also, Grayskull is awesome, thanks a lot for that!

**Pull request merged**
