### PR TITLE
Add thewchan as maintainer

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by thewchan** [comment]
@maresb
@marcelotrevisani
@beckermr
@conda-forge/core 

Another package I'm trying to get onto Conda-forge needs an older version of this one as a dependency. Please add me as a maintainer so I can do that

**Comment by marcelotrevisani** [comment]
hey, no worries, just a friendly reminder that if you need an older version you should create a new branch and integrate the modifications to this other branch

**Review by marcelotrevisani — APPROVED** [review]

**Comment by isuruf** [comment]
@thewchan, please use `conda-forge/core` sparingly and contact us if the feedstock maintainers are unresponsive or they need help.

**Pull request merged**
